
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BookMyTableDataLayer.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ExceptionLogging
{

    public int Id { get; set; }

    public string ExceptionMsg { get; set; }

    public string InnerExceptionMsg { get; set; }

    public string ExceptionType { get; set; }

    public string ExceptionSource { get; set; }

    public string StackTrace { get; set; }

    public Nullable<long> StatusCode { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

}

}
