
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BookMyTableDataLayer.Data
{

using System;
    using System.Collections.Generic;
    
public partial class salesOrderTable
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public salesOrderTable()
    {

        this.salesOrderItemTables = new HashSet<salesOrderItemTable>();

    }


    public int OrderID { get; set; }

    public Nullable<int> HotelId { get; set; }

    public Nullable<int> TableId { get; set; }

    public Nullable<int> TotalQuantity { get; set; }

    public Nullable<int> IsApproveStatus { get; set; }

    public string ApprovalName { get; set; }

    public Nullable<decimal> TotalAmount { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<int> CustomerId { get; set; }

    public Nullable<int> IsPayed { get; set; }

    public Nullable<int> IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<salesOrderItemTable> salesOrderItemTables { get; set; }

}

}
