
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BookMyTableDataLayer.Data
{

using System;
    using System.Collections.Generic;
    
public partial class UserRole
{

    public int RoleId { get; set; }

    public int UserId { get; set; }

    public string RoleDesc { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public byte[] ts { get; set; }

}

}
